name: Build artifact
on:
  push:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  spring-test-ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK #java-8 not supported yet
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven verify phase
        run: mvn --batch-mode verify
      - name: Build with Maven
        run: mvn -DskipTests package
      - uses: actions/upload-artifact@v3
        with:
          name: java-spring-security-test-artifacts
          path: target/*.war
          retention-days: 1
